### ISSUE TITLE
EXIF-Daten zur Höhe und Richtung

### ISSUE THREAD

**Issue by pathmapper** [kreis-viersen/fotostandort#1]
Aktuell werden diese, sofern vorhanden, bei einer Neupositionierung des Markers gelöscht (die Annahme war hier, dass diese ja meistens an der neuen Position nicht mehr stimmen).

Mögliche Alternativen:
1. Die EXIF-Daten zur Höhe und Richtung werden immer behalten.
2. Es kann ausgewählt werden, ob EXIF-Daten zur Höhe und Richtung behalten oder verworfen werden sollen.
3. Es können Angaben zur Höhe und/oder Richtung gemacht werden und diese werden dann in die EXIF-Daten geschrieben.
4. ...

**Comment by pathmapper** [comment]
Zu den Alternativen:

1. ist schnell umgesetzt
2. ist auch schnell umgesetzt, die Benutzeroberfläche hat dann aber einen Knopf mehr
3. ist aufwendiger umzusetzen (soll der Marker die Richtung anzeigen?), die Benutzeroberfläche wird auf jeden Fall umfangreicher

**Comment by stoni100** [comment]
Ziel war nur die betont einfache Korrektur oder Ergänzung der Exif-Koordinaten. Daher sollte das Tool auch nichts anderes ändern (können) ... sonst landen wir bei einem "Super-Exif-Tool"

**Comment by pathmapper** [comment]
EXIF-Daten zur Höhe und Richtung bleiben nun unverändert erhalten (https://github.com/kreis-viersen/fotostandort/commit/1b65066eee7a25d53f54d7c4c71a6165e23272ad).
